FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  gcc-arm-none-eabi \
  git \
  python3 \
  wget \
  unzip \
  libnewlib-arm-none-eabi \
  && rm -rf /var/lib/apt/lists/*

# Clona o pico-sdk
RUN mkdir -p /home/gitpod/pico && cd /home/gitpod/pico && \
    git clone -b master https://github.com/raspberrypi/pico-sdk.git && \
    cd pico-sdk && git submodule update --init
